# Generated by Django 4.1 on 2022-12-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCollection',
            fields=[
                ('complaint', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=30)),
                ('aspect', models.CharField(max_length=30)),
            ],
        ),
    ]
